### ISSUE TITLE
Error shows when run the action node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by node)

### ISSUE THREAD

**Issue by LehaoLin** [inokawa/lang-box#15]
**Describe the bug**

Bug shows when run the action
![image](https://user-images.githubusercontent.com/35103106/193512838-ae572a6f-2f8f-4aa8-be05-2914fa55dd01.png)

**To Reproduce**
Steps to reproduce the behavior.

Just run the `run` action.

**Expected behavior**

Maybe we should revise the nodejs version in the `run.yml` to
```
- name: Setup Node
  uses: actions/setup-node@v2
  with:
     node-version: "18.x"
```

**Additional context**
